
#define ERROR_RESET					0

//2 BLANK ERRORS AT START OF ARRAY   
#define ERROR_GAME_CLOSING			 2	//2 error messages for each
#define ERROR_BANK_MAX_EXCEEDED		 4 
#define ERROR_CREDIT_MAX_EXCEEDED	 6 
#define ERROR_AVOID_COINJAM			 8 
#define ERROR_COLLECT_HANDPAY		10 
#define ERROR_HAND_PAYOUT			12 
#define ERROR_DOOROPEN_DEMO			14 
//2 BLANK ERRORS AT END OF ARRAY

#define MAX_WARNING				18	//TOTAL NUMBER OF ELEMENTS IN ARRAY (14+4)
